name: Send Chat Message

on: [pull_request]

concurrency: build

jobs:
  Test_Init:
    name: Initialize Test Notification
    runs-on: "ubuntu-latest"
    outputs:
      messageTs: ${{ steps.notification.outputs.messageTs }}
    steps:
      - name: what
        run: echo ${{ github.head_ref }}
      - name: Set up notifications
        id: notification
        uses: synapsestudios/build-status@wire-it-up
        with:
          type: "trigger"
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          token: ${{ secrets.SLACK_API_TOKEN }}
          channel: "C020D9LJZHT"
          header: Build ${{ github.run_number }}

  Test_Job:
    name: Send Update to Test Notification
    runs-on: "ubuntu-latest"
    needs: [Test_Init]
    steps:
      - name: Set up notifications
        uses: synapsestudios/build-status@wire-it-up
        with:
          messageTs: ${{ needs.Test_Init.outputs.messageTs }}
          jobStatus: ${{ job.status }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          token: ${{ secrets.SLACK_API_TOKEN }}
          channel: "C020D9LJZHT"
          name: Test Job
