name: Send Chat Message

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  Build:
    name: Build
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
      - uses: c-hive/gha-npm-cache@v1
      - name: Install JS dependencies
        run: npm install
      - name: Build
        run: |
          npm run build
          git config --global user.email "<>"
          git config --global user.name "Github Actions Build"
          git diff-index --quiet HEAD || git commit -am "Build ${{ github.run_number }}"
          git push

  Test:
    name: Send Test Notifications
    runs-on: "ubuntu-latest"
    needs: [Build]
    outputs:
      messageTs: ${{ steps.notification.outputs.messageTs }}
    steps:
      - name: Set up notifications
        id: notification
        uses: synapsestudios/build-status@main
        with:
          type: "trigger"
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          token: ${{ secrets.SLACK_API_TOKEN }}
          channel: "C020D9LJZHT"
          header: Build ${{ github.run_number }}
