name: Send Chat Message

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  Build:
    - uses: actions/checkout@v2
    - uses: c-hive/gha-npm-cache@v1
    - name: Install JS dependencies
      run: npm install
    - name: Build
      run: |
        npm run build
        git commit -am "Build ${{ github.run_number }}"
        git push

  Test:
    name: Initialize_notification
    runs-on: "ubuntu-latest"
    needs: [Build]
    outputs:
      messageTs: ${{ steps.notification.outputs.messageTs }}
    steps:
      - name: Set up notifications
        id: notification
        uses: synapsestudios/build-status@main
        with:
          type: "trigger"
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          token: ${{ secrets.SLACK_API_TOKEN }}
          channel: "C020D9LJZHT"
          header: Build ${{ github.run_number }}
