name: Format and Test
on: [pull_request]
jobs:
  Unit_Test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: "16"
          cache: "npm"

      - name: Install dependencies
        run: npm i

      - name: Check Formatting
        run: npm run prettier:ci

      - name: Test
        run: npm run test

  Build:
    name: Build
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - uses: c-hive/gha-npm-cache@v1
      - name: Install JS dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Push Changes
        continue-on-error: true
        run: |
          git config --global user.email "<>"
          git config --global user.name "Github Actions Build"
          git diff-index --quiet HEAD || git commit -am "[Automated Commit] Build ${{ github.run_number }}"
          git push

  Test_Init:
    name: Initialize Test Notification
    runs-on: "ubuntu-latest"
    needs: [Build]
    outputs:
      messageTs: ${{ steps.notification.outputs.messageTs }}
    steps:
      - name: Set up notifications
        id: notification
        uses: synapsestudios/build-status@wire-it-up
        with:
          type: "trigger"
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          token: ${{ secrets.SLACK_API_TOKEN }}
          channel: "C020D9LJZHT"
          header: Build ${{ github.run_number }}

  Test_Job_Status:
    name: Send Update to Test Notification
    runs-on: "ubuntu-latest"
    needs: [Test_Init]
    steps:
      - name: Notify Job Status
        uses: synapsestudios/build-status@wire-it-up
        with:
          messageTs: ${{ needs.Test_Init.outputs.messageTs }}
          jobStatus: ${{ job.status }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          token: ${{ secrets.SLACK_API_TOKEN }}
          channel: "C020D9LJZHT"
          name: Test Job

  Test_Link:
    name: Append header link
    runs-on: "ubuntu-latest"
    needs: [Test_Init, Test_Job_Status]
    steps:
      - name: Notify Job Status
        uses: synapsestudios/build-status@wire-it-up
        with:
          messageTs: ${{ needs.Test_Init.outputs.messageTs }}
          jobStatus: ${{ job.status }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          token: ${{ secrets.SLACK_API_TOKEN }}
          channel: "C020D9LJZHT"
          name: Test Link
      - name: Append Header Link!
        uses: synapsestudios/build-status@wire-it-up
        with:
          type: "link"
          messageTs: ${{ needs.Test_Init.outputs.messageTs }}
          jobStatus: ${{ job.status }}
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          token: ${{ secrets.SLACK_API_TOKEN }}
          channel: "C020D9LJZHT"
