name: Test
on: [pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: "16"
          cache: "npm"

      - name: Install dependencies
        run: npm i

      - name: Check Formatting
        run: npm run prettier:ci

      - name: Test
        run: npm run test
