name: Format and Test
on: [pull_request]
jobs:
  Unit_Test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: "16"
          cache: "npm"

      - name: Install dependencies
        run: npm i

      - name: Check Formatting
        run: npm run prettier:ci

      - name: Test
        run: npm run test

  Build:
    name: Build
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - uses: c-hive/gha-npm-cache@v1
      - name: Install JS dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Push Changes
        continue-on-error: true
        run: |
          git config --global user.email "<>"
          git config --global user.name "Github Actions Build"
          git diff-index --quiet HEAD || git commit -am "[Automated Commit] Build ${{ github.run_number }}"
          git push
